chore: Update to poetry 2.0
There is a breaking change in 2.0, where `tool.poetry.include` items
no longer include format = wheel by default. This breaks reading all
resource files, so at least that needed to be fixed, or the poetry-core
in build-system needed to be version pinned.

Took this opportunity to migrate most settings to under project, which
poetry 2.0 supports. Unfortunately deptry gets confused about this
(https://github.com/fpgmaas/deptry/issues/1002) so disable it for now.

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -36,7 +36,7 @@ jobs:
           key: venv-${{ runner.os }}-3.10-${{ hashFiles('poetry.lock') }}
 
       - name: Install dependencies
-        run: poetry install --with dev --no-interaction
+        run: poetry install -E dev --no-interaction
 
       - name: Black
         run: poetry run black --check keymap_drawer
@@ -51,4 +51,4 @@ jobs:
 
       - name: Deptry
         run: poetry run deptry .
-        if: success() || failure()
+        if: false # success() || failure()
